"use client";
import { ChangeEvent, useState } from "react";
import { FileUp, CheckCircle2, AlertTriangle, Loader2 } from "lucide-react";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { Alert } from "@/components/ui/alert";
import { api } from "@/lib/api";
interface RealDataStudioModalProps { isOpen: boolean; onClose: () => void; onComplete?: () => void; [key: string]: unknown }
export function RealDataStudioModal({ isOpen, onClose, onComplete }: RealDataStudioModalProps) {
  const [loading, setLoading] = useState(false); const [result, setResult] = useState<any>(null); const [error, setError] = useState<string | null>(null);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const files = Array.from(event.target.files || []); if (!files.length) return; setLoading(true); setError(null); setResult(null); try { setResult(await api.uploadRiskDataset(files)); onComplete?.(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to analyze the dataset."); } finally { setLoading(false); } };
  return <Modal isOpen={isOpen} onClose={onClose} title="Add company dataset" description="Upload company risk data. CRISP validates it and produces the risk analysis and budget recommendation automatically." maxWidth="lg"><div className="space-y-5">{!result && <><label className="flex min-h-52 cursor-pointer flex-col items-center justify-center rounded-2xl border border-dashed border-cyan-400/40 bg-cyan-400/5 p-8 text-center hover:bg-cyan-400/10"><FileUp className="mb-3 h-9 w-9 text-cyan-300" /><span className="font-semibold text-slate-100">{loading ? "Analyzing company data…" : "Choose dataset files"}</span><span className="mt-2 max-w-md text-xs leading-5 text-slate-400">CSV, TSV, or JSON. Required: risk_id, risk_name, current_risk, expected_residual_risk, remediation_cost, available_budget. Optional: cvss_score, business_criticality, threat_activity, exposure.</span><input className="sr-only" type="file" multiple accept=".csv,.tsv,.json,text/csv,text/tab-separated-values,application/json" onChange={upload} disabled={loading} /></label>{loading && <div className="flex justify-center"><Loader2 className="h-5 w-5 animate-spin text-cyan-300" /></div>}</>}{error && <Alert variant="error" title="Dataset rejected">{error}</Alert>}{result && <div className="space-y-4"><Alert variant="success" title="Dataset analyzed">{result.valid_count} valid risk records were analyzed from the uploaded company dataset.</Alert><div className="grid grid-cols-3 gap-3 text-center text-xs"><div className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><b className="block text-lg text-white">{result.optimization.selected_risks.length}</b>Recommended</div><div className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><b className="block text-lg text-white">{result.optimization.deferred_risks.length}</b>Deferred</div><div className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><b className="block text-lg text-cyan-300">{result.optimization.overall_risk_reduction_percent}%</b>Modeled reduction</div></div>{result.invalid_count > 0 && <div className="flex gap-2 text-xs text-amber-300"><AlertTriangle className="h-4 w-4 shrink-0" />{result.invalid_count} invalid row(s) were excluded.</div>}<p className="rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-xs leading-5 text-slate-300"><CheckCircle2 className="mr-1 inline h-4 w-4 text-emerald-300" />{result.optimization.recommendation}</p></div>}<div className="flex justify-end"><Button variant="secondary" onClick={onClose}>{result ? "Close" : "Cancel"}</Button></div></div></Modal>;
}
