import { Risk } from "@/types/risk";
import { Asset } from "@/types/asset";
import { Vulnerability, Threat, SecurityControl, Investment } from "@/types/security";

export const DEMO_ASSETS: Asset[] = [
  {
    id: "ast_payment_api",
    organization_id: "org_default",
    name: "Payment Processing Gateway API",
    asset_type: "API",
    description: "Core payment gateway processing customer credit card transactions and settlements",
    criticality: "Critical",
    business_value: 50000000,
    data_sensitivity: 95,
    internet_exposed: true,
    owner: "Payments Engineering Team",
    environment: "Production",
    status: "Active",
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2024-03-10T11:20:00Z",
    active_risks_count: 2,
    max_residual_risk: 52.03,
  },
  {
    id: "ast_cust_db",
    organization_id: "org_default",
    name: "Primary Customer Core Database",
    asset_type: "Database",
    description: "PostgreSQL cluster housing PII, KYC records, and encrypted auth credentials",
    criticality: "Critical",
    business_value: 85000000,
    data_sensitivity: 98,
    internet_exposed: false,
    owner: "Data Platform Team",
    environment: "Production",
    status: "Active",
    created_at: "2024-01-10T09:30:00Z",
    updated_at: "2024-03-12T14:45:00Z",
    active_risks_count: 1,
    max_residual_risk: 42.65,
  },
  {
    id: "ast_admin_portal",
    organization_id: "org_default",
    name: "Global Operations Admin Portal",
    asset_type: "Portal",
    description: "Internal operational portal for customer support and authorization overrides",
    criticality: "High",
    business_value: 15000000,
    data_sensitivity: 75,
    internet_exposed: true,
    owner: "DevOps & IT Ops",
    environment: "Production",
    status: "Active",
    created_at: "2024-01-20T10:00:00Z",
    updated_at: "2024-02-28T09:15:00Z",
    active_risks_count: 1,
    max_residual_risk: 26.83,
  },
  {
    id: "ast_cloud_storage",
    organization_id: "org_default",
    name: "Customer Documents S3/GCS Bucket",
    asset_type: "Cloud Storage",
    description: "Object storage containing encrypted KYC docs and monthly billing statements",
    criticality: "High",
    business_value: 20000000,
    data_sensitivity: 85,
    internet_exposed: false,
    owner: "Cloud Infrastructure Team",
    environment: "Production",
    status: "Active",
    created_at: "2024-01-18T14:20:00Z",
    updated_at: "2024-03-01T16:00:00Z",
    active_risks_count: 1,
    max_residual_risk: 33.05,
  },
  {
    id: "ast_employee_ep",
    organization_id: "org_default",
    name: "Staff Enterprise Laptops Fleet",
    asset_type: "Endpoint",
    description: "Corporate fleet of 250+ macOS & Windows employee laptops",
    criticality: "Medium",
    business_value: 8000000,
    data_sensitivity: 60,
    internet_exposed: true,
    owner: "IT Support Team",
    environment: "Production",
    status: "Active",
    created_at: "2024-01-05T11:00:00Z",
    updated_at: "2024-03-08T10:30:00Z",
    active_risks_count: 1,
    max_residual_risk: 16.18,
  },
  {
    id: "ast_prod_web",
    organization_id: "org_default",
    name: "Public Marketing & Customer Web App",
    asset_type: "Server",
    description: "Frontend customer-facing web presence and public documentation site",
    criticality: "Medium",
    business_value: 5000000,
    data_sensitivity: 40,
    internet_exposed: true,
    owner: "Growth Engineering Team",
    environment: "Production",
    status: "Active",
    created_at: "2024-02-01T12:00:00Z",
    updated_at: "2024-03-14T08:45:00Z",
    active_risks_count: 0,
    max_residual_risk: 0,
  },
];

export const DEMO_VULNERABILITIES: Vulnerability[] = [
  {
    id: "vuln_rce",
    asset_id: "ast_payment_api",
    asset_name: "Payment Processing Gateway API",
    cve_id: "CVE-2024-21413",
    name: "Remote Code Execution in Parsing Library",
    description: "Unauthenticated RCE vulnerability via deserialization flaws in processing payload",
    cvss_score: 9.8,
    exploitability_score: 90.0,
    severity: "Critical",
    patch_available: true,
    exploit_available: true,
    discovered_at: "2024-03-01T10:00:00Z",
    status: "Open",
    created_at: "2024-03-01T10:00:00Z",
    updated_at: "2024-03-15T09:00:00Z",
  },
  {
    id: "vuln_sqli",
    asset_id: "ast_admin_portal",
    asset_name: "Global Operations Admin Portal",
    cve_id: "CVE-2024-3094",
    name: "SQL Injection in Filtering Parameter",
    description: "Blind SQL injection in operational search filter allows exfiltration of session data",
    cvss_score: 8.6,
    exploitability_score: 80.0,
    severity: "High",
    patch_available: true,
    exploit_available: false,
    discovered_at: "2024-02-20T14:30:00Z",
    status: "In Progress",
    created_at: "2024-02-20T14:30:00Z",
    updated_at: "2024-03-10T12:00:00Z",
  },
  {
    id: "vuln_auth_bypass",
    asset_id: "ast_cust_db",
    asset_name: "Primary Customer Core Database",
    cve_id: "CVE-2023-44487",
    name: "Authentication Bypass & Rapid Reset",
    description: "HTTP/2 rapid reset leading to state corruption and authentication bypass under load",
    cvss_score: 8.2,
    exploitability_score: 75.0,
    severity: "High",
    patch_available: true,
    exploit_available: true,
    discovered_at: "2024-02-15T11:00:00Z",
    status: "Open",
    created_at: "2024-02-15T11:00:00Z",
    updated_at: "2024-03-12T15:00:00Z",
  },
  {
    id: "vuln_cloud_leak",
    asset_id: "ast_cloud_storage",
    asset_name: "Customer Documents S3/GCS Bucket",
    cve_id: "CVE-2024-21626",
    name: "Misconfigured Object ACL Permissions",
    description: "Storage bucket policy allows anonymous read access to specific document subdirectories",
    cvss_score: 7.5,
    exploitability_score: 70.0,
    severity: "High",
    patch_available: true,
    exploit_available: false,
    discovered_at: "2024-03-05T09:15:00Z",
    status: "Open",
    created_at: "2024-03-05T09:15:00Z",
    updated_at: "2024-03-14T11:00:00Z",
  },
  {
    id: "vuln_endpoint_malware",
    asset_id: "ast_employee_ep",
    asset_name: "Staff Enterprise Laptops Fleet",
    cve_id: "CVE-2024-1086",
    name: "Privilege Escalation via Kernel Flaw",
    description: "Local privilege escalation vulnerability on endpoint kernels allowing payload staging",
    cvss_score: 7.8,
    exploitability_score: 65.0,
    severity: "High",
    patch_available: false,
    exploit_available: true,
    discovered_at: "2024-02-10T16:00:00Z",
    status: "Open",
    created_at: "2024-02-10T16:00:00Z",
    updated_at: "2024-03-08T10:00:00Z",
  },
];

export const DEMO_THREATS: Threat[] = [
  {
    id: "tht_ext_apt",
    organization_id: "org_default",
    name: "Advanced Nation-State Financial Threat Actor",
    description: "Targeted cyber-espionage and financial extortion actor actively weaponizing zero-day exploits",
    threat_type: "External Attacker",
    activity_level: 85.0,
    source: "Dark Web & CTI Feeds",
    first_seen: "2023-11-10T00:00:00Z",
    last_seen: "2024-03-15T06:00:00Z",
    created_at: "2023-11-10T00:00:00Z",
  },
  {
    id: "tht_ransomware",
    organization_id: "org_default",
    name: "LockBit Ransomware Syndicate",
    description: "Automated double-extortion ransomware campaigns targeting cloud and on-prem enterprise systems",
    threat_type: "Ransomware",
    activity_level: 90.0,
    source: "US-CERT & Industry Alerts",
    first_seen: "2023-09-01T00:00:00Z",
    last_seen: "2024-03-14T20:00:00Z",
    created_at: "2023-09-01T00:00:00Z",
  },
  {
    id: "tht_cred_theft",
    organization_id: "org_default",
    name: "Mass Credential Stuffing & Session Hijacking",
    description: "Distributed credential stuffing and infostealer malware stealing session tokens",
    threat_type: "Credential Theft",
    activity_level: 80.0,
    source: "Identity Intelligence",
    first_seen: "2023-12-05T00:00:00Z",
    last_seen: "2024-03-15T02:00:00Z",
    created_at: "2023-12-05T00:00:00Z",
  },
  {
    id: "tht_insider",
    organization_id: "org_default",
    name: "Privileged Account Abuse & Misuse",
    description: "Unauthorized access or exfiltration by disgruntled or compromised staff members",
    threat_type: "Insider Threat",
    activity_level: 45.0,
    source: "Internal Audit",
    first_seen: "2024-01-01T00:00:00Z",
    last_seen: "2024-03-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const DEMO_CONTROLS: SecurityControl[] = [
  {
    id: "ctl_waf",
    organization_id: "org_default",
    name: "Cloudflare Enterprise Web Application Firewall",
    control_type: "WAF",
    description: "Cloud-edge inspection with managed OWASP rules and rate limiting",
    effectiveness: 78.0,
    coverage: 85.0,
    status: "Operational",
    created_at: "2023-06-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
  },
  {
    id: "ctl_edr",
    organization_id: "org_default",
    name: "CrowdStrike Falcon Enterprise EDR",
    control_type: "EDR",
    description: "Kernel-level telemetry, automated threat containment, and behavioral blocking",
    effectiveness: 85.0,
    coverage: 92.0,
    status: "Operational",
    created_at: "2023-05-15T00:00:00Z",
    updated_at: "2024-02-15T00:00:00Z",
  },
  {
    id: "ctl_mfa",
    organization_id: "org_default",
    name: "FIDO2 Hardware-backed Multi-Factor Authentication",
    control_type: "MFA",
    description: "Mandatory WebAuthn hardware keys required for all administrative access",
    effectiveness: 92.0,
    coverage: 95.0,
    status: "Operational",
    created_at: "2023-08-01T00:00:00Z",
    updated_at: "2024-01-10T00:00:00Z",
  },
  {
    id: "ctl_encrypt",
    organization_id: "org_default",
    name: "Envelope Encryption with AWS/GCP KMS",
    control_type: "Encryption",
    description: "AES-256 field-level encryption for cardholder data and database at-rest storage",
    effectiveness: 95.0,
    coverage: 98.0,
    status: "Operational",
    created_at: "2023-04-10T00:00:00Z",
    updated_at: "2024-03-05T00:00:00Z",
  },
  {
    id: "ctl_siem",
    organization_id: "org_default",
    name: "Datadog Cloud SIEM & Real-time Threat Detection",
    control_type: "SIEM",
    description: "Centralized ingestion of VPC, audit, and container logs with 24/7 alert paging",
    effectiveness: 75.0,
    coverage: 88.0,
    status: "Operational",
    created_at: "2023-07-20T00:00:00Z",
    updated_at: "2024-02-28T00:00:00Z",
  },
  {
    id: "ctl_backup",
    organization_id: "org_default",
    name: "Immutable Off-site Air-gapped Backups",
    control_type: "Backup",
    description: "Write-once-read-many (WORM) daily snapshots with 1-hour RPO guarantee",
    effectiveness: 90.0,
    coverage: 90.0,
    status: "Operational",
    created_at: "2023-03-01T00:00:00Z",
    updated_at: "2024-03-12T00:00:00Z",
  },
];

export const DEMO_RISKS: Risk[] = [
  {
    id: "rsk_payment_rce",
    organization_id: "org_default",
    asset_id: "ast_payment_api",
    asset_name: "Payment Processing Gateway API",
    vulnerability_id: "vuln_rce",
    vulnerability_name: "Remote Code Execution in Parsing Library (CVE-2024-21413)",
    threat_id: "tht_ext_apt",
    threat_name: "Advanced Nation-State Financial Threat Actor",
    likelihood: 89.7,
    impact: 89.25,
    inherent_risk: 80.05,
    control_effectiveness: 35.0,
    residual_risk: 52.03,
    annual_frequency: 0.35,
    loss_magnitude: 40000000,
    eal: 14000000,
    risk_level: "Very High",
    risk_status: "Active",
    calculation_version: "v1",
    created_at: "2024-03-02T10:00:00Z",
    updated_at: "2024-03-15T08:00:00Z",
    drivers: [
      "Asset is internet-exposed with direct card processing capabilities",
      "Vulnerability exploitability score is 90% with public PoC available",
      "Active CTI indicators observe nation-state actor scanning port 443",
      "Critical data sensitivity with regulatory penalties under PCI-DSS",
    ],
    controls_applied: [
      { id: "ctl_waf", name: "Cloudflare Enterprise WAF", type: "WAF", effectiveness: 78 },
      { id: "ctl_mfa", name: "FIDO2 WebAuthn Admin Keys", type: "MFA", effectiveness: 92 },
    ],
    ai_narrative: {
      summary: "High-consequence remote code execution exposing card processing infrastructure. Although WAF filters known attack vectors, unpatched parser flaws present elevated exploitability.",
      consequences: "Potential unauthorized transaction fabrication, complete database exfiltration, and severe RBI/PCI-DSS non-compliance fines up to ₹2.5 Cr.",
      recommendations: [
        "Deploy emergency parser patch within 24 hours (Option A)",
        "Enforce strict mutual TLS (mTLS) for all ingress API endpoints",
        "Engage 24/7 SOC monitoring for abnormal outbound connections",
      ],
      executive_explanation: "This is the single highest financial liability currently facing the platform, contributing 38% of total organizational Expected Annual Loss.",
    },
  },
  {
    id: "rsk_db_ransomware",
    organization_id: "org_default",
    asset_id: "ast_cust_db",
    asset_name: "Primary Customer Core Database",
    vulnerability_id: "vuln_auth_bypass",
    vulnerability_name: "Authentication Bypass & Rapid Reset (CVE-2023-44487)",
    threat_id: "tht_ransomware",
    threat_name: "LockBit Ransomware Syndicate",
    likelihood: 82.5,
    impact: 94.0,
    inherent_risk: 77.55,
    control_effectiveness: 45.0,
    residual_risk: 42.65,
    annual_frequency: 0.2,
    loss_magnitude: 65000000,
    eal: 13000000,
    risk_level: "Very High",
    risk_status: "Active",
    calculation_version: "v1",
    created_at: "2024-02-18T12:00:00Z",
    updated_at: "2024-03-14T11:00:00Z",
    drivers: [
      "Houses 1.2M customer KYC and banking identity records",
      "Ransomware threat syndicate is active across financial sector",
      "Severe regulatory penalties under DPDP Act 2023",
    ],
    controls_applied: [
      { id: "ctl_encrypt", name: "Envelope Encryption KMS", type: "Encryption", effectiveness: 95 },
      { id: "ctl_backup", name: "Immutable Air-Gapped Backups", type: "Backup", effectiveness: 90 },
    ],
    ai_narrative: {
      summary: "Ransomware extortion targeting core transactional database. Air-gapped backups prevent unrecoverable data loss, but extortion threat over exfiltrated KYC data remains significant.",
      consequences: "Operational halt of all core banking services for estimated 48-72 hours, class-action litigation, and reputational degradation.",
      recommendations: [
        "Implement confidential computing enclaves (Option C)",
        "Isolate database VPC with zero-trust network access policies",
      ],
      executive_explanation: "While backups guarantee data recovery within 1 hour, double extortion risks still represent ₹1.3 Cr in expected annual financial loss.",
    },
  },
  {
    id: "rsk_admin_sqli",
    organization_id: "org_default",
    asset_id: "ast_admin_portal",
    asset_name: "Global Operations Admin Portal",
    vulnerability_id: "vuln_sqli",
    vulnerability_name: "SQL Injection in Filtering Parameter (CVE-2024-3094)",
    threat_id: "tht_cred_theft",
    threat_name: "Mass Credential Stuffing & Session Hijacking",
    likelihood: 74.0,
    impact: 72.5,
    inherent_risk: 53.65,
    control_effectiveness: 50.0,
    residual_risk: 26.83,
    annual_frequency: 0.25,
    loss_magnitude: 15000000,
    eal: 3750000,
    risk_level: "Moderate",
    risk_status: "Active",
    calculation_version: "v1",
    created_at: "2024-02-22T08:00:00Z",
    updated_at: "2024-03-10T16:00:00Z",
    drivers: [
      "Administrative interface with user impersonation capabilities",
      "Blind injection allows query timing attacks against auth tables",
    ],
    controls_applied: [
      { id: "ctl_mfa", name: "Hardware MFA", type: "MFA", effectiveness: 92 },
    ],
  },
  {
    id: "rsk_cloud_leak",
    organization_id: "org_default",
    asset_id: "ast_cloud_storage",
    asset_name: "Customer Documents S3/GCS Bucket",
    vulnerability_id: "vuln_cloud_leak",
    vulnerability_name: "Misconfigured Object ACL Permissions (CVE-2024-21626)",
    threat_id: "tht_ext_apt",
    threat_name: "Advanced Nation-State Financial Threat Actor",
    likelihood: 68.0,
    impact: 81.0,
    inherent_risk: 55.08,
    control_effectiveness: 40.0,
    residual_risk: 33.05,
    annual_frequency: 0.15,
    loss_magnitude: 20000000,
    eal: 3000000,
    risk_level: "Moderate",
    risk_status: "Active",
    calculation_version: "v1",
    created_at: "2024-03-06T10:00:00Z",
    updated_at: "2024-03-14T10:00:00Z",
    drivers: [
      "Overly permissive read ACL on billing statement object prefix",
    ],
  },
  {
    id: "rsk_endpoint_malware",
    organization_id: "org_default",
    asset_id: "ast_employee_ep",
    asset_name: "Staff Enterprise Laptops Fleet",
    vulnerability_id: "vuln_endpoint_malware",
    vulnerability_name: "Privilege Escalation via Kernel Flaw (CVE-2024-1086)",
    threat_id: "tht_ransomware",
    threat_name: "LockBit Ransomware Syndicate",
    likelihood: 62.0,
    impact: 58.0,
    inherent_risk: 35.96,
    control_effectiveness: 55.0,
    residual_risk: 16.18,
    annual_frequency: 0.4,
    loss_magnitude: 8000000,
    eal: 3200000,
    risk_level: "Low",
    risk_status: "Active",
    calculation_version: "v1",
    created_at: "2024-02-12T14:00:00Z",
    updated_at: "2024-03-08T15:00:00Z",
    drivers: [
      "Unpatched kernel versions across 38 macOS/Windows laptops",
      "CrowdStrike EDR blocks payload execution in 85% of scenarios",
    ],
  },
];

export const DEMO_INVESTMENTS: Investment[] = [
  {
    id: "inv_patch_rce",
    organization_id: "org_default",
    name: "Payment Gateway Emergency Patch & Zero-Trust Verification",
    description: "Immediate patching of CVE-2024-21413 with canary rollout and mutual TLS service mesh",
    category: "Remediation",
    cost: 500000,
    implementation_time: "7 days",
    expected_likelihood_reduction: 35.0,
    expected_impact_reduction: 10.0,
    expected_risk_reduction: 28.5,
    expected_eal_reduction: 8500000,
    roi: 1600.0,
    status: "Proposed",
    created_at: "2024-03-05T10:00:00Z",
    updated_at: "2024-03-15T12:00:00Z",
  },
  {
    id: "inv_deploy_waf_rules",
    organization_id: "org_default",
    name: "Next-Gen API Shield & Managed Behavioral WAF",
    description: "Deploy advanced API behavioral anomaly detection on all internet-facing endpoints",
    category: "Tooling",
    cost: 1200000,
    implementation_time: "14 days",
    expected_likelihood_reduction: 25.0,
    expected_impact_reduction: 20.0,
    expected_risk_reduction: 24.0,
    expected_eal_reduction: 7200000,
    roi: 500.0,
    status: "Proposed",
    created_at: "2024-03-08T11:00:00Z",
    updated_at: "2024-03-14T09:00:00Z",
  },
  {
    id: "inv_db_encryption",
    organization_id: "org_default",
    name: "Database Confidential Computing & Tokenization",
    description: "Hardware-enforced confidential computing enclave and customer PII tokenization engine",
    category: "Infrastructure",
    cost: 2500000,
    implementation_time: "45 days",
    expected_likelihood_reduction: 10.0,
    expected_impact_reduction: 45.0,
    expected_risk_reduction: 32.0,
    expected_eal_reduction: 9500000,
    roi: 280.0,
    status: "Proposed",
    created_at: "2024-03-10T14:00:00Z",
    updated_at: "2024-03-15T08:00:00Z",
  },
  {
    id: "inv_staff_training",
    organization_id: "org_default",
    name: "Enterprise Spear-Phishing & Social Engineering Drills",
    description: "Quarterly simulated adversarial campaigns and security champions program",
    category: "Training",
    cost: 400000,
    implementation_time: "30 days",
    expected_likelihood_reduction: 18.0,
    expected_impact_reduction: 5.0,
    expected_risk_reduction: 11.5,
    expected_eal_reduction: 1800000,
    roi: 350.0,
    status: "Approved",
    created_at: "2024-02-15T10:00:00Z",
    updated_at: "2024-03-01T09:00:00Z",
  },
];
